spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zero-death/ConfigServer/
          search-paths: respo
          username: zero-death
          password: shengxingyu123
      label: master

server:
  port: 8086

eureka:
  client:
    service-url:
      deafaulZone: http://localhost:8088/eureka/